services:
  web:
    build:
      .
    command: python /dj_book_proj/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/dj_book_proj
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-n4###qi@_8_aub-v_p9xstep)-%q1g9^k+v%(s3_xirmu_bf01"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:15
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: