# Generated by Django 4.2.4 on 2023-08-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100, verbose_name='Книга')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
        ),
    ]
