# Generated by Django 4.2.4 on 2023-08-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_reviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
